### ISSUE TITLE
FewShotLearning 이용 감정 추출

### ISSUE THREAD

**Issue by Brightyum** [915-Lab/FewShot_function#1]
## 📝 Description
**FewShotLearning**을 통해 텍스트 프롬프트(일기)데이터를 임베딩하여 감정을 추출
## 📍 Todo

- [ ]  예시 데이터들을 바꿔가면서 실험,
- [ ]  텍스트 프롬프트 입력값으로 바꾸기
- [ ]   엑셀 파일 관리가 아닌 데이터베이스 연동
- [ ]   예시 데이터 추가

## 📢 To Reviewers
@effort-type @TAK-C

**Comment by TAK-C** [comment]
확인했습니다. 수고하셨습니다.
